apiVersion: v1
kind: MaturityMetric
metadata:
  name: monitoring-basics
  uid: metric-004
  namespace: ea-maturity
  labels:
    metric: monitoring-basics
    topic: monitoring-observability
    pillar: operational-excellence
    level: '1'
    complexity: low
    assessment-type: qualitative
  annotations:
    display-name: Monitoring basics
    short-description: Basic monitoring involves tracking system performance, uptime, and basic metrics to ensure applicati...
    full-description: >-
      Basic monitoring involves tracking system performance, uptime, and basic metrics to ensure applications are
      running properly.
    documentation: https://docs.company.com/metrics/monitoring-basics
    icon: metric
    color: '#ef4444'
    last-updated: '2025-09-17T02:06:28.381Z'
    maintainer: architecture-team@company.com
    business-impact: Medium
    automation-potential: Medium
spec:
  metric:
    id: monitoring-basics
    name: Monitoring basics
    description: >-
      Basic monitoring involves tracking system performance, uptime, and basic metrics to ensure applications are
      running properly.
  classification:
    topic-id: monitoring-observability
    pillar-id: operational-excellence
    level: 1
    maturity-level: initial
  configuration:
    active: true
    required: true
    weight: 1
    assessment-frequency: quarterly
  assessment:
    type: qualitative
    method: checklist
    scoring:
      scale: 1-3
      min-value: 1
      max-value: 3
      current-value: 1
    criteria:
      level-1:
        score: 1
        name: Initial
        description: >-
          Basic monitoring involves tracking system performance, uptime, and basic metrics to ensure applications are
          running properly.
        risk-level: High
  data-collection:
    sources:
      - Documentation review
      - Technical interviews
      - System analysis
    tools:
      - category: Assessment
        tools:
          - Questionnaires
          - Code analysis
          - Architecture review
  business-context:
    cost-impact:
      level-1: High maintenance costs
    success-metrics:
      - name: Monitoring basics Score
        target: ≥ 2.5
  tags:
    - monitoring
    - observability
status:
  assessment-status: active
  last-assessed: '2025-09-17T02:06:28.381Z'
  next-assessment: '2025-12-16T02:06:28.381Z'
  current-score: 1
  trend: stable
  confidence-level: high
