apiVersion: v1
kind: MaturityMetric
metadata:
  name: security-baseline
  uid: metric-007
  namespace: ea-maturity
  labels:
    metric: security-baseline
    topic: security-fundamentals
    pillar: security
    level: '1'
    complexity: low
    assessment-type: qualitative
  annotations:
    display-name: Security baseline
    short-description: Basic security measures including authentication, authorization, and basic encryption practices....
    full-description: Basic security measures including authentication, authorization, and basic encryption practices.
    documentation: https://docs.company.com/metrics/security-baseline
    icon: metric
    color: '#ef4444'
    last-updated: '2025-09-17T02:06:28.382Z'
    maintainer: architecture-team@company.com
    business-impact: Medium
    automation-potential: Medium
spec:
  metric:
    id: security-baseline
    name: Security baseline
    description: Basic security measures including authentication, authorization, and basic encryption practices.
  classification:
    topic-id: security-fundamentals
    pillar-id: security
    level: 1
    maturity-level: initial
  configuration:
    active: true
    required: true
    weight: 1
    assessment-frequency: quarterly
  assessment:
    type: qualitative
    method: checklist
    scoring:
      scale: 1-3
      min-value: 1
      max-value: 3
      current-value: 1
    criteria:
      level-1:
        score: 1
        name: Initial
        description: Basic security measures including authentication, authorization, and basic encryption practices.
        risk-level: High
  data-collection:
    sources:
      - Documentation review
      - Technical interviews
      - System analysis
    tools:
      - category: Assessment
        tools:
          - Questionnaires
          - Code analysis
          - Architecture review
  business-context:
    cost-impact:
      level-1: High maintenance costs
    success-metrics:
      - name: Security baseline Score
        target: ≥ 2.5
  tags:
    - security
    - baseline
status:
  assessment-status: active
  last-assessed: '2025-09-17T02:06:28.382Z'
  next-assessment: '2025-12-16T02:06:28.382Z'
  current-score: 1
  trend: stable
  confidence-level: high
